import LocalizedStrings from 'react-native-localization'

const LanguageChange = new LocalizedStrings({
  hi: {
    contactNumber: 'संपर्क संख्या',
    username: 'उपयोगकर्ता नाम',
    password: 'पारण शब्द',
    forgotPassword: 'पासवर्ड भूल गए',
    confirmPassword: 'पासवर्ड की पुष्टि कीजिये',
    signIn: 'साइन इन करें',
    noAccount: 'आपका कोई खाता नहीं है?',
    pleaseSignUp: 'कृपया साइन अप करो',
    guestSignIn: 'अतिथि साइन इन',
    registration: 'पंजीकरण',
    fullname: 'पूरा नाम',
    gender: 'लिंग',
    age: 'उम्र',
    signUp: 'साइन अप करें',
    participantNumber: 'आंशिक संख्या',
    state:'राज्य',
    district : 'जिला',
    gramPanchayat : 'पंचायत',
    village: 'गाँव',
    fieldOfficerPassword:'जमीनी स्तर के अधिकारी',
    knowledgeCenter: 'ज्ञान केंद्र',
    importantLinks : 'महत्वपूर्ण लिंक',
    moneyManager : 'मनी मैनेजर',
    contact : 'संपर्क करें',
    message: 'संदेश',
    generalSettings : 'सामान्य सेटिंग्स',
    crops:'फसलों',
    livestock :'पशुधन',
    smallBusiness : 'छोटा व्यवसाय',
    nutrition: 'पोषण बगीचा',
    wash:'वाश',
    health : 'स्वास्थ्य',
    covid: 'कोविड',
    govtSchemes: 'सरकारी योजनाएँ',
    otp: 'ओ टी पी',
    blockPassword: ' पासवर्ड ब्लॉक करें',
    block: 'खंड मैथा',
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करे",
    resetPassword: "नया पासवर्ड बनाए",
    newPassword: "नया पासवर्",
  },
  en: {
    signIn: 'SIGN IN',
    contactNumber: 'CONTACT NUMBER',
    username: 'USERNAME',
    password: 'PASSWORD',
    forgotPassword: 'FORGOT PASSWORD',
    confirmPassword: 'CONFIRM PASSWORD',
    noAccount: 'You dont have an account?',
    pleaseSignUp: 'Please Sign up',
    guestSignIn: 'GUEST SIGN IN',
    registration: 'REGISTRATION',
    fullname: 'FULL-NAME',
    gender: 'GENDER',
    age: 'AGE',
    signUp: 'SIGN UP',
    participantNumber: 'PARTICIPANT NUMBER',
    state:'STATE',
    district : 'DISTRICT',
    gramPanchayat : 'GRAMPANCHAYAT',
    village: 'VILLAGE',
    fieldOfficerPassword:'BLOCK PASSWORD',
    knowledgeCenter: 'KNOWLEDGE CENTER',
    importantLinks : 'IMPORTANT LINKS',
    moneyManager : 'MONEY MANAGER',
    contact : 'CONTACT',
    message: 'MESSAGE',
    generalSettings : 'GENERAL SETTINGS',
    crops:'CROPS',
    livestock :'LIVESTOCK',
    smallBusiness : 'SMALL BUSINESS',
    nutrition: 'NUTRITION GARDEN',
    wash:'WASH',
    health : 'HEALTH',
    covid: 'COVID',
    govtSchemes: 'GOVT SCHEMES',
    otp: 'OTP',
    blockPassword: 'BLOCK PASSWORD',
    block: 'BLOCK',
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    resetPassword: "Create New Password",
    newPassword: "NEW PASSWORD",
  },
  od: {
    signIn: 'ଚୁକ୍ତି କରିବା',
    contactNumber: 'ଯୋଗାଯୋଗ ସଂଖ୍ୟା',
    username: 'ଉପଯୋଗକର୍ତ୍ତା',
    password: 'ପାସୱାର୍ଡ',
    forgotPassword: 'ପାସୱାର୍ଡ଼ ଭୁଲି ଗଲେ କି',
    confirmPassword: 'ପାସ୍ବାଡ଼ ନିସ୍ଚିତ କର',
    noAccount: 'ଆପଣଙ୍କର ଏକ ଖାତା ନାହିଁ?',
    pleaseSignUp: 'ଦୟାକରି ସାଇନ୍ ଅପ୍ କରନ୍ତୁ',
    guestSignIn: 'ସର୍ବଶ୍ରେଷ୍ଠ ସାଇନ୍ ଇନ୍',
    registration: 'ପଞ୍ଜୀକରଣ',
    fullname: 'ପୁରା ନାମ',
    gender: 'ଲିଙ୍ଗ',
    age: 'ବୟସ',
    signUp: 'ସାଇନ୍ ଅପ୍ କରନ୍ତୁ',
    participantNumber: 'ଭାଗୀଦାରୀ ସଂଖ୍ୟା',
    state:'ରାଜ୍ୟ',
    district : 'ଜିଲ୍ଲା',
    gramPanchayat : 'ଗ୍ରାମପଞ୍ଚାୟତ',
    village: 'ଗ୍ରାମ',
    fieldOfficerPassword:'ଫିଲ୍ଡ ଅଫିସ୍ ପାସୱାର୍ଡ',
    knowledgeCenter: 'ଜ୍ଞାନ କେନ୍ଦ୍ର',
    importantLinks : 'ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଲିଙ୍କ୍',
    moneyManager : 'ଟଙ୍କା ପରିଚାଳକ',
    contact : 'ଯୋଗାଯୋଗ କରନ୍ତୁ',
    message: 'ବାର୍ତ୍ତା',
    generalSettings : 'ସାଧାରଣ ସେଟିଂସମୂହ',
    crops:'ଫସଲ',
    livestock :'ପଶୁପାଳନ',
    smallBusiness : 'ଛୋଟ ବ୍ୟବସାୟ',
    nutrition: 'ପୁଷ୍ଟିକର ଉଦ୍ୟାନ',
    wash:'ଧୋଇ ଦିଅ',
    health : 'ସ୍ୱାସ୍ଥ୍ୟ',
    covid: 'covid',
    govtSchemes: 'ଶାସନ ଯୋଜନା',
    otp: 'ଓ ଟି ପି',
    blockPassword: 'ପାସୱାର୍ଡ ଅବରୋଧ କରନ୍ତୁ |',
    block: 'ବ୍ଲକ',
    sendOtp: "OTP ପଠାନ୍ତୁ |",
    verifyOtp: "OTP ଯାଞ୍ଚ କରନ୍ତୁ |",
    resetPassword: "ନୂତନ ପାସୱାର୍ଡ ସୃଷ୍ଟି କରନ୍ତୁ |",
    newPassword: "ନୁତନ ପାସ୍ୱାର୍ଡ",
  }
})

export default LanguageChange